export const EMERGENCY_KEYWORDS = [
  'bleeding',
  'blood loss',
  'poison',
  'poisoned',
  'poisoning',
  'toxic',
  'choking',
  'choke',
  'seizure',
  'seizures',
  'unconscious',
  'collapsed',
  'collapse',
  'difficulty breathing',
  'trouble breathing',
  'not breathing',
  'can not breathe',
  "can't breathe",
  'cannot breathe',
  'hit by car',
  'hit by a car',
  'ran over',
  'run over',
  'car accident',
  'accident',
  'trauma',
  'injured badly',
  'severe injury',
  'broken leg',
  'broken bone',
  'vomiting',
  'vomit',
  'keeps vomiting',
  "won't stop vomiting",
  'cannot stop vomiting',
  'repeated vomiting',
  'severe vomiting',
  'throwing up nonstop',
  'severe pain',
  'extreme pain',
  'bloated stomach',
  'swollen belly',
  'cannot stand',
  "can't stand",
  'not moving',
  'pale gums',
  'blue gums',
  'דימום',
  'מדמם',
  'רעל',
  'הרעלה',
  'מורעל',
  'חנק',
  'נחנק',
  'פרכוס',
  'פרכוסים',
  'איבוד הכרה',
  'חסר הכרה',
  'לא נושם',
  'קשיי נשימה',
  'נדרס',
  'דריסה',
  'נדרסה',
  'תאונה',
  'פגיעה מרכב',
  'רכב פגע',
  'נפגע מרכב',
  'פציעה קשה',
  'נפצע קשה',
  'שבר',
  'רגל שבורה',
  'מקיא',
  'הקאה',
  'הקאות',
  'לא מפסיק להקיא',
  'לא מפסיקה להקיא',
  'הקאות חוזרות',
  'מקיא שוב ושוב',
  'כאב חזק',
  'כאבים חזקים',
  'בטן נפוחה',
  'נפיחות בבטן',
  'לא עומד',
  'לא מצליח לעמוד',
  'לא זז',
  'התמוטט',
  'חניכיים חיוורות',
  'חניכיים כחולות',
] as const;

function normalizeEmergencyText(text: string) {
  return text.toLocaleLowerCase().replace(/\s+/g, ' ').trim();
}

export function containsEmergencyKeyword(text: string) {
  const normalizedText = normalizeEmergencyText(text);

  return EMERGENCY_KEYWORDS.some((keyword) =>
    normalizedText.includes(normalizeEmergencyText(keyword)),
  );
}
